### ISSUE TITLE
Have you tried the base-to-novel generalization and cross-dataset transfer settings?

### ISSUE THREAD

**Issue by machengcheng2016** [geekyutao/TaskRes#3]
Greetings!
Thank you for releasing the TaskRes codes. 
I wonder if you have tried the base-to-novel generalization and cross-dataset transfer settings? Actually, I ran TaskRes on the base-to-novel generalization setting, but got degenerated results (Accs are close to zero for most of datasets). Can you kindly give me some suggestions?

**Comment by geekyutao** [comment]
Hi!
I haven't tried the base-to-novel generalization. However, we did some experiments regarding cross-dataset generalization (on ImageNet dataset variants). Check out the results in our paper.
I think your degenerated results are normal. If you look up to Table 1 in CoCoOp paper, you can find that CoOp's performance also drops on unseen classes. The insight, in my perspective, is that these finetuning methods (CoOp, TaskRes, etc) are for adapting CLIP to a specific task, instead of generalizing to other tasks or classes.
